### ISSUE TITLE
Knowing when a server dies

### ISSUE THREAD

**Issue by perrin4869** [primus/metroplex#10]
I'm trying to create a real time application where I need to keep track of all my users (in real time), and I want to have high availability. Up until now I've been using socket.io, but the clustering support seems to be lackluster at best so I am seriously considering migrating to primus. I do have a few questions:

1) I want to know if a server dies in real time, so that one of the servers left in the cluster can clean up after it. Does metroplex support something like this? If not I'll have to come up with my own solution to the problem.

2) Using metroplex together with omega-supreme and primus-emit or emitter, can you get an acknowledgement when forwarding messages to a certain spark in another server? This would be a killer feature for me since in my case, users can interact individually with each other in real time, and I would like to acknowledge their interactions.

If these two things are available out of the box it'll be an easy choice... otherwise I have to decide in which environment it'll be easier to implement these two things

**Comment by lpinca** [comment]
> 1) I want to know if a server dies in real time, so that one of the servers left in the cluster can clean up after it. Does metroplex support something like this? If not I'll have to come up with my own solution to the problem.

If the server is closed gracefully an `unregister` event is emitted on its metroplex instance and also forwarded to the respective primus instance. Otherwise metroplex will just clean up the registry when it finds that the server has died.

> 2) Using metroplex together with omega-supreme and primus-emit or emitter, can you get an acknowledgement when forwarding messages to a certain spark in another server? This would be a killer feature for me since in my case, users can interact individually with each other in real time, and I would like to acknowledge their interactions.

When you forward a message you get back an object an info object like this:
```js
{ ok: true, send: 1 }
```
This is not exactly an ack as you don't really know if the message reached the client, but is close enough because it means that the receiving server has found the connection internally and sent the message over that connection.

**Comment by perrin4869** [comment]
I see, that's cool! I'm wondering, is there any kind of guarantee as to the timing multiplex finds out that the server died non gracefully? Are the other servers aware of it through some kind of event?

**Comment by perrin4869** [comment]
What about adding new servers dynamically?

**Comment by lpinca** [comment]
> Is there any kind of guarantee as to the timing multiplex finds out that the server died non gracefully?
All the metroplex instances have an internal timer which is configurable. When the timeout expires metroplex update a timestamp and checks if all the servers are still "alive" (if they have updated their timestamp). If a server has not updated its timestamp it is considered dead and removed from the registry.

> Are the other servers aware of it through some kind of event?
No, right now the only way is to query the registry and see if the server is still there.

> What about adding new servers dynamically?
It should work fine.
