### ISSUE TITLE
getting spark objects 

### ISSUE THREAD

**Issue by peacemakr** [primus/metroplex#26]
I can see that messages can be sent to Sparks using spark IDs but how do we get the actual spark object to be used, for example, in primus-emitter.

Something like:
```
primus.getSpark( [<spark ID1>,..], function( err, sparks ){
  sparks[0].send(....
});
```
The reason why I want to use primus-emitter is because I want to get a return value from the client right away on the same object.

**Comment by lpinca** [comment]
You can't get the spark objects of another Primus instance. To get a spark on a given Primus instance use `primus.spark(id)`.

**Comment by peacemakr** [comment]
Ya, but that only works on the local instance. If the user is connected to another instance then it wont work (like you also mentioned). Is there anyway we send a message to remote instance and have it call the client and provide us the result (received from client).

**Comment by lpinca** [comment]
No, the module has not been designed to do this.

**Comment by peacemakr** [comment]
any suggestions on how to go about implementing it myself?

**Comment by lpinca** [comment]
Maybe you can use a custom middleware. Take a look at how [`omega-supreme`](https://github.com/primus/omega-supreme/blob/master/omega.js) works.
