### ISSUE TITLE
send_command is not a function

### ISSUE THREAD

**Issue by siddo420** [primus/metroplex#5]
I am not sure if its an actual issue (could be a documentation bug at least).

I am currently testing metroplex and found out that its somehow dependent on the particular Redis library you're using with it (ie. https://github.com/mranney/node_redis). The reason is that it is using a function that is not supported by one of the popular Redis client libraries ioredis.

For details, see the issue I opened with ioredis --> https://github.com/luin/ioredis/issues/90

**Comment by lpinca** [comment]
Yes, [leverage](https://github.com/observing/leverage) which is a dependecy of `metroplex` uses the `send_command` method of the redis client.

Maybe it makes sense to remove the `leverage` dependency and use the `ioredis` [lua-scripting] (https://github.com/luin/ioredis#lua-scripting) feature.

**Comment by lpinca** [comment]
Closing this as it has been addressed in https://github.com/luin/ioredis/commit/2edc5d1514e502450c01af4c7e1610a641c0f846 and https://github.com/primus/metroplex/pull/7.
