### ISSUE TITLE
change description

### ISSUE THREAD

**Issue by mgutz** [primus/metroplex#9]
The description is cute and all but I could barely make sense of what the project does. Same with omega supreme. It wasn't until I read this [issue](https://github.com/primus/primus/issues/244) that it made sense.

Please change the description or make it more clear what this project does.

**Comment by lpinca** [comment]
> Metroplex a Redis based spark/connection registry for Primus.

I think that this description gives you an idea of what metroplex does.
If you think you can improve it, please send a pr with and we will most likely merge it instantly.

**Comment by mgutz** [comment]
@3rd-Eden's clarifications: 

The metroplex project keeps track of all connections in redis so it can find the server address for each given spark id.

Omega supreme adds messaging between multiple primus servers. It needs a server address, spark id and message and the server will then send the correct message to the connected client.

**Comment by 3rd-Eden** [comment]
@mgutz Descriptions are updated, thanks for the copy <3!
